services:
  portainer:
    hostname: portainer
    image: "portainer/portainer-ce:latest"
    restart: unless-stopped
    ports:
      - "443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/data